**mounting google drive**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

**Dataset address**

In [2]:
InputDataFile = '/content/drive/MyDrive/Colab Notebooks/Data management Project/Data Management Project - Datafiles/Part 09 - Original Dataset + Sentiments Summaries NER and embeddings Added/compact-finalized-515k-hotel-dataset-with-sentiments-summaries-NER-and-embeddings.csv'

### **all the functions that are needed to do this step by step process**

In [3]:
import csv
import pandas as pd
import numpy as np

In [4]:
# Read the CSV file using pandas
data = pd.read_csv(InputDataFile)
# number_of_training_cases = len(data.index)
print(len(data.index))

17365

In [5]:
df_temp = data

In [6]:
import pandas as pd
import numpy as np

# Assuming you have a DataFrame named df_temp with a column 'Hotel_Name_values'

# Define the possible values for 'place_type' and 'food_grade'
place_types = ['hotels', 'Clubs', 'Restaurants', 'Cafes', 'Bars']
food_grades = ['B', 'A', 'AA', 'AAA']

# Seed for reproducibility
np.random.seed(42)

# Group by 'Hotel_Name_values'
grouped = df_temp.groupby('Hotel_Name_values')

# Create a dictionary to store the assigned values for each group
values_dict = {}

# Assign the same values for each group
for name, group in grouped:
    place_type = np.random.choice(place_types)
    food_grade = np.random.choice(food_grades)
    is_favorite = 'false'

    values_dict[name] = {'place_type': place_type, 'food_grade': food_grade, 'isFavorite': is_favorite}

# Apply the assigned values to the DataFrame
df_temp['place_type'] = df_temp['Hotel_Name_values'].map(lambda x: values_dict[x]['place_type'])
df_temp['food_grade'] = df_temp['Hotel_Name_values'].map(lambda x: values_dict[x]['food_grade'])
df_temp['isFavorite'] = df_temp['Hotel_Name_values'].map(lambda x: values_dict[x]['isFavorite'])

# Display the resulting DataFrame
print(df_temp)

       Sequence_Number  Sequence     Hotel_Name_values  \
0                    0     33862  '11 Cadogan Gardens'
1                    1     33780  '11 Cadogan Gardens'
2                    2     33778  '11 Cadogan Gardens'
3                    3     33853  '11 Cadogan Gardens'
4                    4     33849  '11 Cadogan Gardens'
...                ...       ...                   ...
17360            33314    252763             TheWesley
17361            33315    252736             TheWesley
17362            33316    252711             TheWesley
17363            33317    252152             TheWesley
17364            33318    252667             TheWesley

                                    Hotel_Address_values Review_Date_values  \
0      '11 Cadogan Gardens Sloane Square Kensington a...         2015-08-13
1      '11 Cadogan Gardens Sloane Square Kensington a...         2015-09-10
2      '11 Cadogan Gardens Sloane Square Kensington a...         2015-10-01
3      '11 Cadogan Gardens Sloane Square Kensington a...         2015-11-05
4      '11 Cadogan Gardens Sloane Square Kensington a...         2015-12-01
...                                                  ...                ...
17360  '81 103 Euston Street Camden London NW1 2EZ Un...         2016-03-01
17361  '81 103 Euston Street Camden London NW1 2EZ Un...         2016-04-01
17362  '81 103 Euston Street Camden London NW1 2EZ Un...         2016-05-01
17363  '81 103 Euston Street Camden London NW1 2EZ Un...         2016-06-03
17364  '81 103 Euston Street Camden London NW1 2EZ Un...         2016-07-03

       Average_Score_values Reviewer_Nationality_values  \
0                       8.7                  ' Latvia '
1                       8.7          ' United Kingdom '
2                       8.7          ' United Kingdom '
3                       8.7          ' United Kingdom '
4                       8.7          ' United Kingdom '
...                     ...                         ...
17360                   8.0          ' United Kingdom '
17361                   8.0          ' United Kingdom '
17362                   8.0          ' United Kingdom '
17363                   8.0          ' United Kingdom '
17364                   8.0          ' United Kingdom '

      Negative_sentence_column_Sentiment  \
0                               positive
1                               negative
2                               positive
3                               negative
4                               positive
...                                  ...
17360                           positive
17361                           positive
17362                           positive
17363                           negative
17364                           positive

       Negative_sentence_column_Positivity_Percentage  \
0                                                 0.0
1                                                 0.0
2                                                19.4
3                                                 0.0
4                                                 0.0
...                                               ...
17360                                             0.0
17361                                             0.0
17362                                            57.3
17363                                             9.5
17364                                             0.0

       Negative_sentence_column_Negativity_Percentage  ...   longitude  \
0                                                 0.0  ...  -0.1592347
1                                                10.8  ...  -0.1592347
2                                                 0.0  ...  -0.1592347
3                                                15.5  ...  -0.1592347
4                                                 0.0  ...  -0.1592347
...                                               ...  ...         ...
17360                                             0.0  ...  -0.1361682
17361                                             0.0  ...  -0.1361682
17362                                             0.0  ...  -0.1361682
17363                                            22.4  ...  -0.1361682
17364                                             0.0  ...  -0.1361682

                              Positive_Review_Embeddings Negative_Review  \
0      [{'sentence': "' Nice location good service ni...             NaN
1      [{'sentence': "' FOOD WAS GOOD AND SERVICE'", ...             NaN
2      [{'sentence': "' We stayed in a junior suite f...             NaN
3      [{'sentence': "' Leaving'", 'embedding': [-0.6...             NaN
4      [{'sentence': "' The staff were excellent help...             NaN
...                                                  ...             ...
17360  [{'sentence': "' the food was really good'", '...             NaN
17361  [{'sentence': "' The double bed was two single...             NaN
17362  [{'sentence': "' Lovely staff was given a love...             NaN
17363  [{'sentence': "' Location and price excellent ...             NaN
17364  [{'sentence': "' Very clean '", 'embedding': [...             NaN

       Review_Total_Negative_Word_Counts  Review_Total_Positive_Word_Counts  \
0                                    NaN                                NaN
1                                    NaN                                NaN
2                                    NaN                                NaN
3                                    NaN                                NaN
4                                    NaN                                NaN
...                                  ...                                ...
17360                                NaN                                NaN
17361                                NaN                                NaN
17362                                NaN                                NaN
17363                                NaN                                NaN
17364                                NaN                                NaN

            Nationalities                               Positive_Review_Dict  \
0              ['Latvia']  [{'Sequence': 33862, 'Positive_Review': "' Nic...
1      ['United Kingdom']  [{'Sequence': 33780, 'Positive_Review': "' FOO...
2      ['United Kingdom']  [{'Sequence': 33778, 'Positive_Review': "' We ...
3      ['United Kingdom']  [{'Sequence': 33853, 'Positive_Review': "' Lea...
4      ['United Kingdom']  [{'Sequence': 33849, 'Positive_Review': "' The...
...                   ...                                                ...
17360  ['United Kingdom']  [{'Sequence': 252212, 'Positive_Review': "' th...
17361  ['United Kingdom']  [{'Sequence': 252736, 'Positive_Review': "' Th...
17362  ['United Kingdom']  [{'Sequence': 252710, 'Positive_Review': "' Go...
17363  ['United Kingdom']  [{'Sequence': 252151, 'Positive_Review': "' Ou...
17364  ['United Kingdom']  [{'Sequence': 252667, 'Positive_Review': "' Ve...

        place_type food_grade isFavorite
0            Cafes          B      false
1            Cafes          B      false
2            Cafes          B      false
3            Cafes          B      false
4            Cafes          B      false
...            ...        ...        ...
17360  Restaurants        AAA      false
17361  Restaurants        AAA      false
17362  Restaurants        AAA      false
17363  Restaurants        AAA      false
17364  Restaurants        AAA      false

[17365 rows x 28 columns]

In [7]:
# Assuming df_temp is your DataFrame
columns_to_drop = ['Negative_Review', 'Review_Total_Negative_Word_Counts', 'Review_Total_Positive_Word_Counts']

# Drop the specified columns
df_temp_column_dropped = df_temp.drop(columns=columns_to_drop)

# Display the resulting DataFrame
print(df_temp_column_dropped)

       Sequence_Number  Sequence     Hotel_Name_values  \
0                    0     33862  '11 Cadogan Gardens'
1                    1     33780  '11 Cadogan Gardens'
2                    2     33778  '11 Cadogan Gardens'
3                    3     33853  '11 Cadogan Gardens'
4                    4     33849  '11 Cadogan Gardens'
...                ...       ...                   ...
17360            33314    252763             TheWesley
17361            33315    252736             TheWesley
17362            33316    252711             TheWesley
17363            33317    252152             TheWesley
17364            33318    252667             TheWesley

                                    Hotel_Address_values Review_Date_values  \
0      '11 Cadogan Gardens Sloane Square Kensington a...         2015-08-13
1      '11 Cadogan Gardens Sloane Square Kensington a...         2015-09-10
2      '11 Cadogan Gardens Sloane Square Kensington a...         2015-10-01
3      '11 Cadogan Gardens Sloane Square Kensington a...         2015-11-05
4      '11 Cadogan Gardens Sloane Square Kensington a...         2015-12-01
...                                                  ...                ...
17360  '81 103 Euston Street Camden London NW1 2EZ Un...         2016-03-01
17361  '81 103 Euston Street Camden London NW1 2EZ Un...         2016-04-01
17362  '81 103 Euston Street Camden London NW1 2EZ Un...         2016-05-01
17363  '81 103 Euston Street Camden London NW1 2EZ Un...         2016-06-03
17364  '81 103 Euston Street Camden London NW1 2EZ Un...         2016-07-03

       Average_Score_values Reviewer_Nationality_values  \
0                       8.7                  ' Latvia '
1                       8.7          ' United Kingdom '
2                       8.7          ' United Kingdom '
3                       8.7          ' United Kingdom '
4                       8.7          ' United Kingdom '
...                     ...                         ...
17360                   8.0          ' United Kingdom '
17361                   8.0          ' United Kingdom '
17362                   8.0          ' United Kingdom '
17363                   8.0          ' United Kingdom '
17364                   8.0          ' United Kingdom '

      Negative_sentence_column_Sentiment  \
0                               positive
1                               negative
2                               positive
3                               negative
4                               positive
...                                  ...
17360                           positive
17361                           positive
17362                           positive
17363                           negative
17364                           positive

       Negative_sentence_column_Positivity_Percentage  \
0                                                 0.0
1                                                 0.0
2                                                19.4
3                                                 0.0
4                                                 0.0
...                                               ...
17360                                             0.0
17361                                             0.0
17362                                            57.3
17363                                             9.5
17364                                             0.0

       Negative_sentence_column_Negativity_Percentage  ...  \
0                                                 0.0  ...
1                                                10.8  ...
2                                                 0.0  ...
3                                                15.5  ...
4                                                 0.0  ...
...                                               ...  ...
17360                                             0.0  ...
17361                                             0.0  ...
17362                                             0.0  ...
17363                                            22.4  ...
17364                                             0.0  ...

                               Cleaned_Positive_Summmary Reviewer_Score  \
0                 Location. The room was cozy and clean.           10.0
1      Location great location near champs elysees an...            6.3
2      Location great location near champs elysees an...           10.0
3                 Location. The room was cozy and clean.            4.2
4                 Location. The room was cozy and clean.           10.0
...                                                  ...            ...
17360  Location close to euston train station. Locati...            8.3
17361  Nice hotel. Great breakfast. The people the se...            9.2
17362  Location. Rooms were well thought out and very...            9.6
17363  Location very good close to euston and the nor...            6.7
17364  As a staying guest the staff were friendly and...            7.9

                latitude   longitude  \
0             51.4936161  -0.1592347
1             51.4936161  -0.1592347
2             51.4936161  -0.1592347
3             51.4936161  -0.1592347
4             51.4936161  -0.1592347
...                  ...         ...
17360  51.52653529999999  -0.1361682
17361  51.52653529999999  -0.1361682
17362  51.52653529999999  -0.1361682
17363  51.52653529999999  -0.1361682
17364  51.52653529999999  -0.1361682

                              Positive_Review_Embeddings       Nationalities  \
0      [{'sentence': "' Nice location good service ni...          ['Latvia']
1      [{'sentence': "' FOOD WAS GOOD AND SERVICE'", ...  ['United Kingdom']
2      [{'sentence': "' We stayed in a junior suite f...  ['United Kingdom']
3      [{'sentence': "' Leaving'", 'embedding': [-0.6...  ['United Kingdom']
4      [{'sentence': "' The staff were excellent help...  ['United Kingdom']
...                                                  ...                 ...
17360  [{'sentence': "' the food was really good'", '...  ['United Kingdom']
17361  [{'sentence': "' The double bed was two single...  ['United Kingdom']
17362  [{'sentence': "' Lovely staff was given a love...  ['United Kingdom']
17363  [{'sentence': "' Location and price excellent ...  ['United Kingdom']
17364  [{'sentence': "' Very clean '", 'embedding': [...  ['United Kingdom']

                                    Positive_Review_Dict   place_type  \
0      [{'Sequence': 33862, 'Positive_Review': "' Nic...        Cafes
1      [{'Sequence': 33780, 'Positive_Review': "' FOO...        Cafes
2      [{'Sequence': 33778, 'Positive_Review': "' We ...        Cafes
3      [{'Sequence': 33853, 'Positive_Review': "' Lea...        Cafes
4      [{'Sequence': 33849, 'Positive_Review': "' The...        Cafes
...                                                  ...          ...
17360  [{'Sequence': 252212, 'Positive_Review': "' th...  Restaurants
17361  [{'Sequence': 252736, 'Positive_Review': "' Th...  Restaurants
17362  [{'Sequence': 252710, 'Positive_Review': "' Go...  Restaurants
17363  [{'Sequence': 252151, 'Positive_Review': "' Ou...  Restaurants
17364  [{'Sequence': 252667, 'Positive_Review': "' Ve...  Restaurants

      food_grade isFavorite
0              B      false
1              B      false
2              B      false
3              B      false
4              B      false
...          ...        ...
17360        AAA      false
17361        AAA      false
17362        AAA      false
17363        AAA      false
17364        AAA      false

[17365 rows x 25 columns]

In [8]:
df = df_temp_column_dropped
print(df.columns)

Index(['Sequence_Number', 'Sequence', 'Hotel_Name_values',
       'Hotel_Address_values', 'Review_Date_values', 'Average_Score_values',
       'Reviewer_Nationality_values', 'Negative_sentence_column_Sentiment',
       'Negative_sentence_column_Positivity_Percentage',
       'Negative_sentence_column_Negativity_Percentage',
       'Cleaned_Negative_Summmary', 'Positive_Review',
       'Positive_sentence_column_Sentiment',
       'Positive_sentence_column_Positivity Percentage',
       'Positive_sentence_column_Negativity Percentage',
       'Cleaned_Positive_Summmary', 'Reviewer_Score', 'latitude', 'longitude',
       'Positive_Review_Embeddings', 'Nationalities', 'Positive_Review_Dict',
       'place_type', 'food_grade', 'isFavorite'],
      dtype='object')

In [9]:
# Print columns with types
print(df.dtypes)

Sequence_Number                                     int64
Sequence                                            int64
Hotel_Name_values                                  object
Hotel_Address_values                               object
Review_Date_values                                 object
Average_Score_values                              float64
Reviewer_Nationality_values                        object
Negative_sentence_column_Sentiment                 object
Negative_sentence_column_Positivity_Percentage    float64
Negative_sentence_column_Negativity_Percentage    float64
Cleaned_Negative_Summmary                          object
Positive_Review                                    object
Positive_sentence_column_Sentiment                 object
Positive_sentence_column_Positivity Percentage    float64
Positive_sentence_column_Negativity Percentage    float64
Cleaned_Positive_Summmary                          object
Reviewer_Score                                    float64
latitude                                           object
longitude                                          object
Positive_Review_Embeddings                         object
Nationalities                                      object
Positive_Review_Dict                               object
place_type                                         object
food_grade                                         object
isFavorite                                         object
dtype: object

In [ ]:
selected_columns = [
    'latitude',
    'longitude',
    'Positive_Review_Embeddings',
    'Positive_Review_Dict'
]

# Display the selected columns with a head of 4
df_selected = df[selected_columns].head(4)
display(df_selected)

In [11]:
# Display the first few rows of the dataset
print("First few rows of the dataset:")
display(df.head(3))

# Display the column names
print("\nColumn names:")
display(df.columns)

# Display data types of each column
print("\nData types:")
display(df.dtypes)

# Display summary statistics
print("\nSummary statistics:")
display(df.describe())

# Display information about missing values
print("\nMissing values information:")
display(df.isnull().sum())

# Display unique values in the 'Hotel_Name_values' column
print("\nUnique hotel names:")
display(df['Hotel_Name_values'].unique())

# Display details of the 'Positive_Review_Embeddings' column (replace with your actual column name)
print("\nDetails of 'Positive_Review_Embeddings' column:")
display(df['Positive_Review_Embeddings'].head())

# Display details of the 'Positive_Review_Dict' column
print("\nDetails of 'Positive_Review_Dict' column:")
display(df['Positive_Review_Dict'].head())

First few rows of the dataset:

,Sequence_Number,Sequence,Hotel_Name_values,Hotel_Address_values,Review_Date_values,Average_Score_values,Reviewer_Nationality_values,Negative_sentence_column_Sentiment,Negative_sentence_column_Positivity_Percentage,Negative_sentence_column_Negativity_Percentage,...,Cleaned_Positive_Summmary,Reviewer_Score,latitude,longitude,Positive_Review_Embeddings,Nationalities,Positive_Review_Dict,place_type,food_grade,isFavorite
0,0,33862,'11 Cadogan Gardens','11 Cadogan Gardens Sloane Square Kensington a...,2015-08-13,8.7,' Latvia ',positive,0.0,0.0,...,Location. The room was cozy and clean.,10.0,51.4936161,-0.1592347,"[{'sentence': ""' Nice location good service ni...",['Latvia'],"[{'Sequence': 33862, 'Positive_Review': ""' Nic...",Cafes,B,false
1,1,33780,'11 Cadogan Gardens','11 Cadogan Gardens Sloane Square Kensington a...,2015-09-10,8.7,' United Kingdom ',negative,0.0,10.8,...,Location great location near champs elysees an...,6.3,51.4936161,-0.1592347,"[{'sentence': ""' FOOD WAS GOOD AND SERVICE'"", ...",['United Kingdom'],"[{'Sequence': 33780, 'Positive_Review': ""' FOO...",Cafes,B,false
2,2,33778,'11 Cadogan Gardens','11 Cadogan Gardens Sloane Square Kensington a...,2015-10-01,8.7,' United Kingdom ',positive,19.4,0.0,...,Location great location near champs elysees an...,10.0,51.4936161,-0.1592347,"[{'sentence': ""' We stayed in a junior suite f...",['United Kingdom'],"[{'Sequence': 33778, 'Positive_Review': ""' We ...",Cafes,B,false

Column names:

Index(['Sequence_Number', 'Sequence', 'Hotel_Name_values',
       'Hotel_Address_values', 'Review_Date_values', 'Average_Score_values',
       'Reviewer_Nationality_values', 'Negative_sentence_column_Sentiment',
       'Negative_sentence_column_Positivity_Percentage',
       'Negative_sentence_column_Negativity_Percentage',
       'Cleaned_Negative_Summmary', 'Positive_Review',
       'Positive_sentence_column_Sentiment',
       'Positive_sentence_column_Positivity Percentage',
       'Positive_sentence_column_Negativity Percentage',
       'Cleaned_Positive_Summmary', 'Reviewer_Score', 'latitude', 'longitude',
       'Positive_Review_Embeddings', 'Nationalities', 'Positive_Review_Dict',
       'place_type', 'food_grade', 'isFavorite'],
      dtype='object')

Data types:

Sequence_Number                                     int64
Sequence                                            int64
Hotel_Name_values                                  object
Hotel_Address_values                               object
Review_Date_values                                 object
Average_Score_values                              float64
Reviewer_Nationality_values                        object
Negative_sentence_column_Sentiment                 object
Negative_sentence_column_Positivity_Percentage    float64
Negative_sentence_column_Negativity_Percentage    float64
Cleaned_Negative_Summmary                          object
Positive_Review                                    object
Positive_sentence_column_Sentiment                 object
Positive_sentence_column_Positivity Percentage    float64
Positive_sentence_column_Negativity Percentage    float64
Cleaned_Positive_Summmary                          object
Reviewer_Score                                    float64
latitude                                           object
longitude                                          object
Positive_Review_Embeddings                         object
Nationalities                                      object
Positive_Review_Dict                               object
place_type                                         object
food_grade                                         object
isFavorite                                         object
dtype: object

Summary statistics:

,Sequence_Number,Sequence,Average_Score_values,Negative_sentence_column_Positivity_Percentage,Negative_sentence_column_Negativity_Percentage,Positive_sentence_column_Positivity Percentage,Positive_sentence_column_Negativity Percentage,Reviewer_Score
count,17365.000000,17365.000000,17365.000000,17365.000000,17365.000000,17365.000000,17365.000000,17365.000000
mean,16744.649928,258970.573913,8.464302,8.901181,7.468552,45.047515,0.862367,8.496009
std,9565.947799,148583.042409,0.545053,17.294935,15.819511,27.947991,4.567859,1.577274
min,0.000000,114.000000,5.200000,0.000000,0.000000,0.000000,0.000000,2.500000
25%,8557.000000,132121.000000,8.100000,0.000000,0.000000,27.000000,0.000000,7.500000
50%,16792.000000,256725.000000,8.500000,0.000000,0.000000,50.800000,0.000000,9.000000
75%,24946.000000,389782.000000,8.900000,12.300000,8.000000,67.200000,0.000000,9.600000
max,33318.000000,515738.000000,9.800000,100.000000,100.000000,100.000000,100.000000,10.000000

Missing values information:

Sequence_Number                                   0
Sequence                                          0
Hotel_Name_values                                 0
Hotel_Address_values                              0
Review_Date_values                                0
Average_Score_values                              0
Reviewer_Nationality_values                       0
Negative_sentence_column_Sentiment                0
Negative_sentence_column_Positivity_Percentage    0
Negative_sentence_column_Negativity_Percentage    0
Cleaned_Negative_Summmary                         0
Positive_Review                                   0
Positive_sentence_column_Sentiment                0
Positive_sentence_column_Positivity Percentage    0
Positive_sentence_column_Negativity Percentage    0
Cleaned_Positive_Summmary                         0
Reviewer_Score                                    0
latitude                                          0
longitude                                         0
Positive_Review_Embeddings                        0
Nationalities                                     0
Positive_Review_Dict                              0
place_type                                        0
food_grade                                        0
isFavorite                                        0
dtype: int64

Unique hotel names:

array(["'11 Cadogan Gardens'", "'1K Hotel'",
       "'25hours Hotel beim MuseumsQuartier'", ..., 'Montfleuri',
       'Rathbone', 'TheWesley'], dtype=object)

Details of 'Positive_Review_Embeddings' column:

0    [{'sentence': "' Nice location good service ni...
1    [{'sentence': "' FOOD WAS GOOD AND SERVICE'", ...
2    [{'sentence': "' We stayed in a junior suite f...
3    [{'sentence': "' Leaving'", 'embedding': [-0.6...
4    [{'sentence': "' The staff were excellent help...
Name: Positive_Review_Embeddings, dtype: object

Details of 'Positive_Review_Dict' column:

0    [{'Sequence': 33862, 'Positive_Review': "' Nic...
1    [{'Sequence': 33780, 'Positive_Review': "' FOO...
2    [{'Sequence': 33778, 'Positive_Review': "' We ...
3    [{'Sequence': 33853, 'Positive_Review': "' Lea...
4    [{'Sequence': 33849, 'Positive_Review': "' The...
Name: Positive_Review_Dict, dtype: object

In [12]:
print(len(df))

17365

In [13]:
df02= df

,Sequence_Number,Sequence,Hotel_Name_values,Hotel_Address_values,Review_Date_values,Average_Score_values,Reviewer_Nationality_values,Negative_sentence_column_Sentiment,Negative_sentence_column_Positivity_Percentage,Negative_sentence_column_Negativity_Percentage,...,Cleaned_Positive_Summmary,Reviewer_Score,latitude,longitude,Positive_Review_Embeddings,Nationalities,Positive_Review_Dict,place_type,food_grade,isFavorite
0,0,33862,11 Cadogan Gardens,11 Cadogan Gardens Sloane Square Kensington an...,2015-08-13,8.7,Latvia,positive,0.0,0.0,...,Location. The room was cozy and clean.,10.0,51.4936161,-0.1592347,"[{sentence: "" Nice location good service nice ...",[Latvia],"[{Sequence: 33862, Positive_Review: "" Nice loc...",Cafes,B,false
1,1,33780,11 Cadogan Gardens,11 Cadogan Gardens Sloane Square Kensington an...,2015-09-10,8.7,United Kingdom,negative,0.0,10.8,...,Location great location near champs elysees an...,6.3,51.4936161,-0.1592347,"[{sentence: "" FOOD WAS GOOD AND SERVICE"", embe...",[United Kingdom],"[{Sequence: 33780, Positive_Review: "" FOOD WAS...",Cafes,B,false
2,2,33778,11 Cadogan Gardens,11 Cadogan Gardens Sloane Square Kensington an...,2015-10-01,8.7,United Kingdom,positive,19.4,0.0,...,Location great location near champs elysees an...,10.0,51.4936161,-0.1592347,"[{sentence: "" We stayed in a junior suite for ...",[United Kingdom],"[{Sequence: 33778, Positive_Review: "" We staye...",Cafes,B,false
3,3,33853,11 Cadogan Gardens,11 Cadogan Gardens Sloane Square Kensington an...,2015-11-05,8.7,United Kingdom,negative,0.0,15.5,...,Location. The room was cozy and clean.,4.2,51.4936161,-0.1592347,"[{sentence: "" Leaving"", embedding: [-0.6105284...",[United Kingdom],"[{Sequence: 33853, Positive_Review: "" Leaving""...",Cafes,B,false
4,4,33849,11 Cadogan Gardens,11 Cadogan Gardens Sloane Square Kensington an...,2015-12-01,8.7,United Kingdom,positive,0.0,0.0,...,Location. The room was cozy and clean.,10.0,51.4936161,-0.1592347,"[{sentence: "" The staff were excellent helpful...",[United Kingdom],"[{Sequence: 33849, Positive_Review: "" The staf...",Cafes,B,false

In [39]:
# Assuming 'HotelNamedValues' is the column name
unique_hotel_names = df03['Hotel_Name_values'].unique()

# Display the unique values as a set
print(len(set(unique_hotel_names)))
print(set(unique_hotel_names))

1492

In [40]:
data = df03

In [41]:
!pip install sentence_transformers

Requirement already satisfied: sentence_transformers in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: transformers<5.0.0,>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (4.35.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (4.66.1)
Requirement already satisfied: torch>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (2.1.0+cu118)
Requirement already satisfied: torchvision in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (0.16.0+cu118)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (1.23.5)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (1.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (1.11.3)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (3.8.1)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (0.1.99)
Requirement already satisfied: huggingface-hub>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (0.19.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence_transformers) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence_transformers) (2023.6.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence_transformers) (2.31.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence_transformers) (6.0.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence_transformers) (4.5.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence_transformers) (23.2)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence_transformers) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence_transformers) (3.2.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence_transformers) (3.1.2)
Requirement already satisfied: triton==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence_transformers) (2.1.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.6.0->sentence_transformers) (2023.6.3)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.6.0->sentence_transformers) (0.15.0)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.6.0->sentence_transformers) (0.4.0)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk->sentence_transformers) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk->sentence_transformers) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->sentence_transformers) (3.2.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.10/dist-packages (from torchvision->sentence_transformers) (9.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.6.0->sentence_transformers) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence_transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence_transformers) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence_transformers) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence_transformers) (2023.7.22)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.6.0->sentence_transformers) (1.3.0)

## **Recommendation system related**

In [42]:
datatempDF = data

In [43]:
display(datatempDF.head(5))

,Sequence_Number,Sequence,Hotel_Name_values,Hotel_Address_values,Review_Date_values,Average_Score_values,Reviewer_Nationality_values,Negative_sentence_column_Sentiment,Negative_sentence_column_Positivity_Percentage,Negative_sentence_column_Negativity_Percentage,...,Cleaned_Positive_Summmary,Reviewer_Score,latitude,longitude,Positive_Review_Embeddings,Nationalities,Positive_Review_Dict,place_type,food_grade,isFavorite
0,0,33862,11 Cadogan Gardens,11 Cadogan Gardens Sloane Square Kensington an...,2015-08-13,8.7,Latvia,positive,0.0,0.0,...,Location. The room was cozy and clean.,10.0,51.4936161,-0.1592347,"[{sentence: "" Nice location good service nice ...",[Latvia],"[{Sequence: 33862, Positive_Review: "" Nice loc...",Cafes,B,false
1,1,33780,11 Cadogan Gardens,11 Cadogan Gardens Sloane Square Kensington an...,2015-09-10,8.7,United Kingdom,negative,0.0,10.8,...,Location great location near champs elysees an...,6.3,51.4936161,-0.1592347,"[{sentence: "" FOOD WAS GOOD AND SERVICE"", embe...",[United Kingdom],"[{Sequence: 33780, Positive_Review: "" FOOD WAS...",Cafes,B,false
2,2,33778,11 Cadogan Gardens,11 Cadogan Gardens Sloane Square Kensington an...,2015-10-01,8.7,United Kingdom,positive,19.4,0.0,...,Location great location near champs elysees an...,10.0,51.4936161,-0.1592347,"[{sentence: "" We stayed in a junior suite for ...",[United Kingdom],"[{Sequence: 33778, Positive_Review: "" We staye...",Cafes,B,false
3,3,33853,11 Cadogan Gardens,11 Cadogan Gardens Sloane Square Kensington an...,2015-11-05,8.7,United Kingdom,negative,0.0,15.5,...,Location. The room was cozy and clean.,4.2,51.4936161,-0.1592347,"[{sentence: "" Leaving"", embedding: [-0.6105284...",[United Kingdom],"[{Sequence: 33853, Positive_Review: "" Leaving""...",Cafes,B,false
4,4,33849,11 Cadogan Gardens,11 Cadogan Gardens Sloane Square Kensington an...,2015-12-01,8.7,United Kingdom,positive,0.0,0.0,...,Location. The room was cozy and clean.,10.0,51.4936161,-0.1592347,"[{sentence: "" The staff were excellent helpful...",[United Kingdom],"[{Sequence: 33849, Positive_Review: "" The staf...",Cafes,B,false

In [44]:
try:
    datatempDF['Positive_Review_Embeddings'] = datatempDF['Positive_Review_Embeddings'].apply(ast.literal_eval)
except Exception as e:
    print(f"Error: {e}")
    # Print the specific rows causing the error
    problematic_rows = datatempDF[datatempDF['Positive_Review_Embeddings'].apply(lambda x: not isinstance(x, dict))]['Positive_Review_Embeddings']
    print("Problematic rows:")
    print(problematic_rows)

Error: malformed node or string on line 1: <ast.Name object at 0x7a5b6c643f40>
Problematic rows:
0        [{sentence: " Nice location good service nice ...
1        [{sentence: " FOOD WAS GOOD AND SERVICE", embe...
2        [{sentence: " We stayed in a junior suite for ...
3        [{sentence: " Leaving", embedding: [-0.6105284...
4        [{sentence: " The staff were excellent helpful...
                               ...
17360    [{sentence: " the food was really good", embed...
17361    [{sentence: " The double bed was two single be...
17362    [{sentence: " Lovely staff was given a lovely ...
17363    [{sentence: " Location and price excellent for...
17364    [{sentence: " Very clean ", embedding: [-0.571...
Name: Positive_Review_Embeddings, Length: 17365, dtype: object

# **func 01**
**Get a specific number of recommendations from the model**

In [45]:
import torch
import pandas as pd
from sentence_transformers import SentenceTransformer, util
import ast

def get_recommendations(query_sentence, dataframe, num_recommendations=5):
    rank = 0
    # Load the Sentence Transformers model
    model = SentenceTransformer('jinaai/jina-embedding-t-en-v1')

    print(len(dataframe))

    try:
        dataframe['Positive_Review_Embeddings'] = dataframe['Positive_Review_Embeddings'].apply(ast.literal_eval)
    except Exception as e:
        # print(f"Error: {e}")
        problematic_rows = dataframe[dataframe['Positive_Review_Embeddings'].apply(lambda x: not isinstance(x, dict))]['Positive_Review_Embeddings']
        # print("Problematic rows:")
        # print(problematic_rows)

    # Extract necessary columns
    positive_reviews_data = dataframe[['Positive_Review', 'Positive_Review_Embeddings', 'Cleaned_Positive_Summmary']]

    # Filter out rows with missing embeddings
    positive_reviews_data = positive_reviews_data.dropna(subset=['Positive_Review_Embeddings'])

    # Extract embeddings and sentences
    positive_embeddings = positive_reviews_data['Positive_Review_Embeddings'].apply(lambda x: x[0]['embedding']).tolist()
    positive_sentences = positive_reviews_data['Positive_Review'].tolist()
    cleaned_positive_sentences = positive_reviews_data['Cleaned_Positive_Summmary'].tolist()

    # Encode the query sentence
    query_embedding = model.encode([query_sentence], convert_to_tensor=True)

    # Check the shape of the query_embedding and positive_embeddings
    print("Query Embedding Shape:", query_embedding.shape)
    print("Positive Embeddings Shape:", torch.tensor(positive_embeddings).shape)

    # Calculate cosine similarities between the query and positive review embeddings
    similarities = util.pytorch_cos_sim(query_embedding, torch.tensor(positive_embeddings))[0]

    # Create a DataFrame to store results
    results_df = pd.DataFrame({
        'Review': positive_sentences,
        'Cleaned_Positive_Summmary': cleaned_positive_sentences,
        'Positive_Review_Embeddings': positive_embeddings,
        'Similarity': similarities.tolist()
    })

    # Rank the recommendations based on similarity
    ranked_results = results_df.sort_values(by='Similarity', ascending=False).head(num_recommendations)

    # Prepare the output list of dictionaries
    output_list = []
    for idx, row in ranked_results.iterrows():
        output_list.append({
            'rank': rank + 1,
            'similarity_score': row['Similarity'],
            'entire_row': dataframe.loc[idx].to_dict()
        })
        rank += 1

    return output_list

# **func 01 - execution**

In [46]:
# Example usage:
query_sentence = "Seeking a business-friendly hotel with a quiet ambiance, fast Wi-Fi, and a well-equipped conference room. Ideally, it should be centrally located and have good options for dining nearby. Any recommendations for a productive stay?"

# Get recommendations for the given query sentence (e.g., top 5 recommendations)
recommendations = get_recommendations(query_sentence, datatempDF, num_recommendations=60)

# Print the recommendations
for recommendation in recommendations:
    print(recommendation)

17365

TypeError: ignored

In [ ]:
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer, util
import ast
import torch
import copy
import pickle
from datetime import datetime
import datetime as dt
import random
from typing import List, Dict


class RecommendationFunctions:
    def __init__(self, dataframe, csv_structure, csv_path):

        # current dataset storing related
        self.dataframe = dataframe
        # previous preferences storing related
        self.previous_preferences = []
        # new reviews preferences storing related
        # Create a DataFrame template with the provided CSV structure
        template_df = pd.DataFrame(columns=csv_structure.keys())

        # Save the template DataFrame as a CSV file
        template_df.to_csv(csv_path, index=False)

        self.csv_path = csv_path



    def get_highest_ranked_recommendations(self, head_size):                                                                  # Recommandations
        rank = 0
        """
        Get the highest-ranked set of recommendations based on the rows with the same month as the current date.

        Parameters:
        - head_size (int): The number of rows to retrieve.

        Returns:
        - highest_ranked_recommendations (pd.DataFrame): A DataFrame with highest-ranked hotel recommendations.
        """
        # Convert 'Review_Date_values' to datetime format
        self.dataframe['Review_Date_values'] = pd.to_datetime(self.dataframe['Review_Date_values'])

        # Get the current month
        current_month = dt.datetime.now().month

        # Filter rows with the same month as the current date
        current_month_data = self.dataframe[self.dataframe['Review_Date_values'].dt.month == current_month]

        # Assuming 'Reviewer_Score' is the column representing rankings
        highest_ranked_recommendations = current_month_data.sort_values(by='Average_Score_values', ascending=False).head(head_size)

        output_list = []
        for idx, row in highest_ranked_recommendations.iterrows():
            output_list.append({
                'rank': rank + 1,
                'similarity_score': -1,
                'entire_row': self.dataframe.loc[idx].to_dict()
            })
            rank += 1

        return output_list


    # Function 01: Add Data to Previous Preferences
    def add_to_previous_preferences(self, sentence):
        formatted_entry = {
            'sentence': sentence,
            'datetimerecorded': datetime.now()
        }

        self.previous_preferences.append(formatted_entry)
        print(self.previous_preferences)


    # Function 02: Get Recommendations Based on Previous Preferences
    def get_recommendations_from_previous(self, query_sentence, num_recommendations=5):                                       # Recommandations
        # Call get_recommendations method
        return self.get_recommendations(query_sentence, num_recommendations, use_previous=True)


    # Function 01: Get Recommendations
    def get_recommendations(self, query_sentence, num_recommendations=5, use_previous=False):                                 # Recommandations
        rank = 0
        model = SentenceTransformer('jinaai/jina-embedding-t-en-v1')

        if use_previous:
            # Use the previous preferences for recommendations
            if not self.previous_preferences:
                print("No previous preferences available.")
                return []

            # Combine previous preferences into a single string
            previous_preferences_text = ' '.join(entry['sentence'] for entry in self.previous_preferences)
            query_sentence = previous_preferences_text + ' ' + query_sentence

        try:
            self.dataframe['Positive_Review_Embeddings'] = self.dataframe['Positive_Review_Embeddings'].apply(ast.literal_eval)
        except Exception as e:
            problematic_rows = self.dataframe[self.dataframe['Positive_Review_Embeddings'].apply(lambda x: not isinstance(x, dict))]['Positive_Review_Embeddings']

        # Use the entire dataset for recommendations
        positive_reviews_data = self.dataframe[['Positive_Review', 'Positive_Review_Embeddings', 'Cleaned_Positive_Summmary']]

        positive_reviews_data = positive_reviews_data.dropna(subset=['Positive_Review_Embeddings'])

        positive_embeddings = positive_reviews_data['Positive_Review_Embeddings'].apply(lambda x: x[0]['embedding']).tolist()
        positive_sentences = positive_reviews_data['Positive_Review'].tolist()
        cleaned_positive_sentences = positive_reviews_data['Cleaned_Positive_Summmary'].tolist()

        if not positive_embeddings:
            print("No positive embeddings available.")
            return []

        query_embedding = model.encode([query_sentence], convert_to_tensor=True)

        # Debugging: Print the shapes of the input matrices
        print("Query embedding shape:", query_embedding.shape)
        print("Positive embeddings shape:", torch.tensor(positive_embeddings).shape)

        similarities = util.pytorch_cos_sim(query_embedding, torch.tensor(positive_embeddings))[0]

        results_df = pd.DataFrame({
            'Review': positive_sentences,
            'Cleaned_Positive_Summmary': cleaned_positive_sentences,
            'Positive_Review_Embeddings': positive_embeddings,
            'Similarity': similarities.tolist()
        })

        ranked_results = results_df.sort_values(by='Similarity', ascending=False).head(num_recommendations)

        output_list = []
        for idx, row in ranked_results.iterrows():
            output_list.append({
                'rank': rank + 1,
                'similarity_score': row['Similarity'],
                'entire_row': self.dataframe.loc[idx].to_dict()
            })
            rank += 1

        return output_list



    # Function 04: Initial Recommendations
    def initial_recommendations(self, num_recommendations=5):                                                                       # Recommandations
        # Check if there are entries in the previous preferences list
        if self.previous_preferences:
            # Get half of the recommendations from previous preferences
            num_previous_recommendations = num_recommendations // 2
            previous_recommendations = self.get_recommendations_from_previous('', num_previous_recommendations)
            print(f"Using {len(previous_recommendations)} recommendations from previous preferences.")
        else:
            previous_recommendations = []
            print("No previous preferences available.")

        # Get the remaining recommendations from the highest-ranked entries in the dataset
        num_remaining_recommendations = num_recommendations - len(previous_recommendations)
        highest_ranked_recommendations = self.get_highest_ranked_recommendations(num_remaining_recommendations)
        print(f"Using {len(highest_ranked_recommendations)} recommendations from the highest-ranked entries.")

        # Combine the recommendations
        combined_recommendations = previous_recommendations + highest_ranked_recommendations

        return combined_recommendations


    # Function 02: Filter Rows
    def filter_rows(self, column_name, column_value):
        filtered_df = self.dataframe[(self.dataframe[column_name]) == column_value]
        return filtered_df

    # Function 03: Get Item by Rank from Recommendations
    def get_item_by_rank_from_recommendations(self, recommendations, desired_rank):
        if 1 <= desired_rank <= len(recommendations):
            item = recommendations[desired_rank - 1]
            return item
        else:
            print("Invalid desired rank. Please provide a rank within the valid range.")
            return None

    # Function 04: Get Attribute Keys
    def get_attribute_keys(self, recommendation):
        return list(recommendation.keys())

    # Function 05: Get Attribute Value
    def get_attribute_value(self, recommendation, key):
        return recommendation.get(key)

    # Function 06: Get Column Names from Entire Row
    def get_column_names_from_entire_row(self, entire_row):
        return list(entire_row.keys())

    # Function 07: Get Column Value from Entire Row
    def get_column_value_from_entire_row(self, entire_row, column_name):
        return entire_row.get(column_name)

    # Function 08: Edit Column Value
    def edit_column_value(self, row, column_name, new_value):
        updated_row = copy.deepcopy(row)
        entire_row = updated_row.get("entire_row", {})
        entire_row[column_name] = new_value
        updated_row["entire_row"] = entire_row
        return updated_row

    # Function 09: Get Dataset Size
    def get_dataset_size(self):
        return len(self.dataframe)

    # Function 10: Add New Hotel Data Feedback Loop
    def add_new_hotel_data_feedback_loop(self, new_data,):     # Feedback Loop
        # Read the existing feedback loop CSV file
        try:
            existing_df = pd.read_csv(self.csv_path)
        except FileNotFoundError:
            print("Feedback loop CSV file not found.")
            return

        # Append the new data to the existing DataFrame
        new_df = pd.DataFrame(new_data, index=[0])
        updated_df = pd.concat([existing_df, new_df], ignore_index=True)

        # Save the updated DataFrame back to the CSV file
        updated_df.to_csv(self.csv_path, index=False)

        # Update the current DataFrame in the class
        self.dataframe = updated_df


    def read_feedback_loop_csv(self, num_rows):                # Feedback Loop
        # Read the existing feedback loop CSV file
        try:
            existing_df = pd.read_csv(self.csv_path)
        except FileNotFoundError:
            print("Feedback loop CSV file not found.")
            return pd.DataFrame()

        # Check if the requested number of rows is greater than available
        if num_rows >= len(existing_df):
            return existing_df.sample(frac=1).to_dict(orient='records')

        # Randomly select a specified number of unique rows
        selected_rows = existing_df.sample(n=num_rows, replace=False)
        return selected_rows.to_dict(orient='records')


    # Function 11: Save Recommendation Model
    def save_model(self, output_file_path):
        """
        Save the model and dataset using pickle.

        Parameters:
        - output_file_path (str): The file path to save the model and dataset.
        """
        with open(output_file_path, 'wb') as file:
            pickle.dump({
                'dataframe': self.dataframe,
                'functions': {
                    'get_highest_ranked_recommendations': self.get_highest_ranked_recommendations,
                    'add_to_previous_preferences': self.add_to_previous_preferences,
                    'get_recommendations_from_previous': self.get_recommendations_from_previous,
                    'get_recommendations': self.get_recommendations,
                    'initial_recommendations': self.initial_recommendations,
                    'filter_rows': self.filter_rows,
                    'get_item_by_rank_from_recommendations': self.get_item_by_rank_from_recommendations,
                    'get_attribute_keys': self.get_attribute_keys,
                    'get_attribute_value': self.get_attribute_value,
                    'get_column_names_from_entire_row': self.get_column_names_from_entire_row,
                    'get_column_value_from_entire_row': self.get_column_value_from_entire_row,
                    'edit_column_value': self.edit_column_value,
                    'get_dataset_size': self.get_dataset_size,
                    'add_new_hotel_data_feedback_loop': self.add_new_hotel_data_feedback_loop,
                    'read_feedback_loop_csv': self.read_feedback_loop_csv,
                    'save_model': self.save_model
                }
            }, file)
        print(f"Model and dataset saved to: {output_file_path}")

In [ ]:
# Example Usage
csv_structure_new_columns = {
    'Hotel_Address': 'str',
    'Review_Date': 'str',
    'Average_Score': 'float',
    'Hotel_Name': 'str',
    'Reviewer_Nationality': 'str',
    'Negative_Review': 'str',
    'Review_Total_Negative_Word_Counts': 'int',
    'Positive_Review': 'str',
    'Review_Total_Positive_Word_Counts': 'int',
    'Reviewer_Score': 'float',
    'Total_Number_of_Reviews_Reviewer_Has_Given': 'int',
    'Total_Number_of_Reviews': 'int',
    'Tags': 'str',
    'days_since_review': 'str',
    'Additional_Number_of_Scoring': 'int',
    'lat': 'float',
    'lng': 'float'
}

In [37]:
csv_path = '/content/drive/MyDrive/Colab Notebooks/Data management Project/Data Management Project - Final model/feedback_loop.csv'

recommendation_system_new_columns = RecommendationFunctions(datatempDF, csv_structure_new_columns, csv_path)

NameError: ignored

## Model Save

In [222]:
# # Save the model and dataset
recommendation_system_new_columns.save_model( '/content/drive/MyDrive/Colab Notebooks/Data management Project/Data Management Project - Final model/recommendation_model.pkl')

Model and dataset saved to: /content/drive/MyDrive/Colab Notebooks/Data management Project/Data Management Project - Final model/recommendation_model.pkl